package com.sam;


import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.List;

import org.apache.commons.lang3.time.StopWatch;

import com.sam.engine.SortEngine;
import com.sam.factory.SortEngineFactory;

public final class SortConsoleInterpret {

	public void start() {
		sout("Welcome to array sorter!");
		String algorithm = queryConsoleUser("Which algorithm would you like to use? Default: Quicksort."
				+ "\nQuicksort"
				+ "\nBogosort"
				+ "\nBubble sort");
		String detail = queryConsoleUser("Would you like a display of the progress of the algorithm? Y/n Default:n");
		if(myList.size() == 0){
			String quantity = queryConsoleUser("How many autogenerated items in the list? Default: 8");
			initInvertedList(myList, quantity);
		}
		
		SortEngine mySortingEngine = factory.getNewOrDefault(algorithm, detail);
		sout("Starting sorting of " + myList.size() + " elements with" + mySortingEngine.getName() + " algorithm.");
		startMeasuringTime();
		mySortingEngine.sort(myList);
		double myTime = getMeasuredTime();
		stopMeasuringTime();
		sout("Hello :D, your " + myList.size() + " element list has been sorted and it took " + myTime + " seconds to sort.");
		sout(myList.toString());
	}
	
	public SortConsoleInterpret(List<Integer> givenList, String sortingAlgorithm){
		if(givenList == null){
			myList = new ArrayList<Integer>();
		} else {
			myList = givenList;
		}
	}
	
/***
 * Inner workings
 */

	private List<Integer> myList;
	private BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
	private SortEngineFactory factory = new SortEngineFactory(); 
	private StopWatch myWatch = new StopWatch();
	
	private static void initInvertedList(List<Integer> list, String length){
		int items = 8;
		try{
			items = Integer.parseInt(length);
		} catch (NumberFormatException e){	
		}
		initInvertedList(list, items);
	}
	
	private static void initInvertedList(List<Integer> list, int length){
		list.clear();
		for (int i = length; i > 0; i--) {
			list.add(i);
		}
	}
	
	private String queryConsoleUser(String text){
		System.out.println(text);
		try {
			return br.readLine();
		} catch (IOException e) {
			return "";
		}
	}
	
	private void startMeasuringTime(){
		myWatch.start();
		myWatch.split();
	}
	
	private void stopMeasuringTime(){
		myWatch.stop();
	}
	
	private double getMeasuredTime(){
		return myWatch.getSplitTime() == 0.0 ? 0 : myWatch.getSplitTime() / 1000;
	}
	
	private void sout(String text){
		System.out.println(text);
	}
}
